//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_PayRoll.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayRollInfo_Tab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PayRollInfo_Tab()
        {
            this.PayRoll_Tab = new HashSet<PayRoll_Tab>();
        }
    
        public int PayRollInfoID { get; set; }
        public Nullable<decimal> BaseSalary { get; set; }
        public Nullable<decimal> BreakfastDeduction { get; set; }
        public Nullable<decimal> SavingDeduction { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual Employees_Tab Employees_Tab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayRoll_Tab> PayRoll_Tab { get; set; }
    }
}
