//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_PayRoll.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenAuth
    {
        public int TokenAuthID { get; set; }
        public Nullable<System.Guid> Token { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<byte> TokenStatusID { get; set; }
    
        public virtual TokenStatus TokenStatus { get; set; }
    }
}
