// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebPayRoll_.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Api Model Employee: Holds information related to Employees
    /// </summary>
    public partial class AMEmployee
    {
        /// <summary>
        /// Initializes a new instance of the AMEmployee class.
        /// </summary>
        public AMEmployee() { }

        /// <summary>
        /// Initializes a new instance of the AMEmployee class.
        /// </summary>
        public AMEmployee(int? employeeID = default(int?), string name = default(string), string lastNames = default(string), DateTime? admissionDate = default(DateTime?), int? roleID = default(int?), string email = default(string), string password = default(string), bool? active = default(bool?), string roleName = default(string), Guid? token = default(Guid?))
        {
            EmployeeID = employeeID;
            Name = name;
            LastNames = lastNames;
            AdmissionDate = admissionDate;
            RoleID = roleID;
            Email = email;
            Password = password;
            Active = active;
            RoleName = roleName;
            Token = token;
        }

        /// <summary>
        /// Employee ID
        /// </summary>
        [JsonProperty(PropertyName = "employeeID")]
        public int? EmployeeID { get; set; }

        /// <summary>
        /// Employee Name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Employee Last Names
        /// </summary>
        [JsonProperty(PropertyName = "lastNames")]
        public string LastNames { get; set; }

        /// <summary>
        /// Employee Admission Date
        /// </summary>
        [JsonProperty(PropertyName = "admissionDate")]
        public DateTime? AdmissionDate { get; set; }

        /// <summary>
        /// Employee Role ID
        /// </summary>
        [JsonProperty(PropertyName = "roleID")]
        public int? RoleID { get; set; }

        /// <summary>
        /// Employee Email
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// Employee Password
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

        /// <summary>
        /// Employee Status
        /// </summary>
        [JsonProperty(PropertyName = "active")]
        public bool? Active { get; set; }

        /// <summary>
        /// Employee Role Name
        /// </summary>
        [JsonProperty(PropertyName = "roleName")]
        public string RoleName { get; set; }

        /// <summary>
        /// Token authorization
        /// </summary>
        [JsonProperty(PropertyName = "token")]
        public Guid? Token { get; set; }

    }
}
