// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebPayRoll_.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Holds information returned by a WebApi
    /// </summary>
    public partial class AMLoginEntity
    {
        /// <summary>
        /// Initializes a new instance of the AMLoginEntity class.
        /// </summary>
        public AMLoginEntity() { }

        /// <summary>
        /// Initializes a new instance of the AMLoginEntity class.
        /// </summary>
        public AMLoginEntity(string userName = default(string), string password = default(string))
        {
            UserName = userName;
            Password = password;
        }

        /// <summary>
        /// User name
        /// </summary>
        [JsonProperty(PropertyName = "userName")]
        public string UserName { get; set; }

        /// <summary>
        /// User name
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

    }
}
