// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebPayRoll_
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// PayRollInfo operations.
    /// </summary>
    public partial interface IPayRollInfo
    {
        /// <summary>
        /// Get a PayRollInfo from an Employee
        /// </summary>
        /// <param name='payRollInfo'>
        /// PayRoll Info model
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Responser>> GetWithHttpMessagesAsync(AMPayRollInfo payRollInfo, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Get a PayRollInfo from an Employee
        /// </summary>
        /// <param name='payRollInfo'>
        /// PayRoll Info model
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Responser>> GetInfoByIDWithHttpMessagesAsync(AMPayRollInfo payRollInfo, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Get PayRolls Info
        /// </summary>
        /// <param name='payRollInfo'>
        /// PayRoll Info model
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Responser>> GetAllWithHttpMessagesAsync(AMPayRollInfo payRollInfo, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Adds a PayRollInfo for an employee within Employee PayRoll
        /// </summary>
        /// <param name='payRollInfo'>
        /// PayRollInfo to add to current Employee
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Responser>> PostWithHttpMessagesAsync(AMPayRollInfo payRollInfo, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Updates a PayRollInfo for an employee within Employee PayRoll
        /// </summary>
        /// <param name='payRollInfo'>
        /// PayRollInfo to add to current Employee
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Responser>> PutWithHttpMessagesAsync(AMPayRollInfo payRollInfo, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Deletes a PayRollInfo for an employee within Employee PayRoll
        /// </summary>
        /// <param name='payRollInfo'>
        /// PayRollInfo to add to current Employee
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Responser>> DeleteWithHttpMessagesAsync(AMPayRollInfo payRollInfo, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Generate Token Auth
        /// </summary>
        /// <param name='userId'>
        /// ID
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Responser>> CreateTokenAuthWithHttpMessagesAsync(string userId = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Generate Token Auth
        /// </summary>
        /// <param name='userId'>
        /// ID
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Responser>> DisableTokenAuthWithHttpMessagesAsync(string userId = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Validates Login a User authorization
        /// </summary>
        /// <param name='token'>
        /// ID
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<Responser>> ValidateAuthorizationWithHttpMessagesAsync(string token = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
