//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPayRoll_.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_Tab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees_Tab()
        {
            this.PayRollInfo_Tab = new HashSet<PayRollInfo_Tab>();
        }
    
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public string LastNames { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.Guid> Token { get; set; }
    
        public virtual Role_Cat Role_Cat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayRollInfo_Tab> PayRollInfo_Tab { get; set; }
    }
}
